#!/usr/bin/env bash
# PAGANINI AIOS — One-line installer
# curl -fsSL https://raw.githubusercontent.com/juboyy/paganini-aios/main/install.sh | sh
#
# Installs: Python 3.11+, git, paganini CLI
# Supports: macOS (arm64/x86_64), Ubuntu/Debian, Fedora/RHEL, Alpine

set -euo pipefail

VERSION="0.1.0"
REPO="https://github.com/juboyy/paganini-aios.git"
INSTALL_DIR="${PAGANINI_HOME:-$HOME/.paganini}"
BIN_DIR="${PAGANINI_BIN:-/usr/local/bin}"

# ── Colors ──────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; PURPLE='\033[0;35m'; NC='\033[0m'

info()  { printf "${BLUE}▸${NC} %s\n" "$1"; }
ok()    { printf "${GREEN}✓${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}⚠${NC} %s\n" "$1"; }
fail()  { printf "${RED}✗${NC} %s\n" "$1"; exit 1; }

# ── Banner ──────────────────────────────────────────────
cat << 'BANNER'

  ╔══════════════════════════════════════════════╗
  ║                                              ║
  ║   🎻  PAGANINI AIOS                          ║
  ║   AI Operating System for Financial Markets  ║
  ║                                              ║
  ╚══════════════════════════════════════════════╝

BANNER

printf "  ${PURPLE}v${VERSION}${NC} · Installing...\n\n"

# ── Detect OS ───────────────────────────────────────────
detect_os() {
  OS="$(uname -s)"
  ARCH="$(uname -m)"
  case "$OS" in
    Linux*)  OS_TYPE="linux" ;;
    Darwin*) OS_TYPE="macos" ;;
    *)       fail "Unsupported OS: $OS" ;;
  esac
  info "Detected: $OS_TYPE ($ARCH)"
}

# ── Check / Install Python ─────────────────────────────
ensure_python() {
  if command -v python3 &>/dev/null; then
    PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
    PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)
    if [ "$PY_MAJOR" -ge 3 ] && [ "$PY_MINOR" -ge 11 ]; then
      ok "Python $PY_VERSION found"
      return
    else
      warn "Python $PY_VERSION found, but 3.11+ required"
    fi
  fi

  info "Installing Python 3.11+..."
  case "$OS_TYPE" in
    macos)
      if command -v brew &>/dev/null; then
        brew install python@3.11
      else
        fail "Install Homebrew first: https://brew.sh"
      fi
      ;;
    linux)
      if command -v apt-get &>/dev/null; then
        sudo apt-get update -qq && sudo apt-get install -y -qq python3.11 python3.11-venv python3-pip
      elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3.11 python3.11-pip
      elif command -v apk &>/dev/null; then
        sudo apk add python3 py3-pip
      else
        fail "Could not install Python. Install Python 3.11+ manually."
      fi
      ;;
  esac
  ok "Python installed"
}

# ── Check git ───────────────────────────────────────────
ensure_git() {
  if command -v git &>/dev/null; then
    ok "git found"
    return
  fi

  info "Installing git..."
  case "$OS_TYPE" in
    macos)  xcode-select --install 2>/dev/null || true ;;
    linux)
      if command -v apt-get &>/dev/null; then
        sudo apt-get install -y -qq git
      elif command -v dnf &>/dev/null; then
        sudo dnf install -y git
      elif command -v apk &>/dev/null; then
        sudo apk add git
      fi
      ;;
  esac
  ok "git installed"
}

# ── Clone or update ────────────────────────────────────
install_paganini() {
  if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing installation..."
    cd "$INSTALL_DIR" && git pull --ff-only origin main
    ok "Updated to latest"
  else
    info "Cloning paganini-aios..."
    git clone --depth 1 "$REPO" "$INSTALL_DIR"
    ok "Cloned to $INSTALL_DIR"
  fi
}

# ── Setup venv + install ───────────────────────────────
setup_env() {
  cd "$INSTALL_DIR"

  if [ ! -d ".venv" ]; then
    info "Creating virtual environment..."
    python3 -m venv .venv
  fi

  info "Installing dependencies..."
  .venv/bin/pip install --quiet --upgrade pip
  .venv/bin/pip install --quiet -e .
  ok "Dependencies installed"
}

# ── Create wrapper script ──────────────────────────────
create_wrapper() {
  WRAPPER="$BIN_DIR/paganini"

  # Try without sudo first, fall back to sudo
  if [ -w "$BIN_DIR" ] 2>/dev/null; then
    SUDO=""
  else
    SUDO="sudo"
  fi

  $SUDO tee "$WRAPPER" > /dev/null << EOF
#!/usr/bin/env bash
# PAGANINI AIOS wrapper — auto-generated by install.sh
export PAGANINI_HOME="$INSTALL_DIR"
exec "$INSTALL_DIR/.venv/bin/paganini" "\$@"
EOF

  $SUDO chmod +x "$WRAPPER"
  ok "CLI available at: $WRAPPER"
}

# ── Verify ─────────────────────────────────────────────
verify() {
  if command -v paganini &>/dev/null; then
    ok "Installation verified"
  else
    warn "paganini not in PATH. Add $BIN_DIR to your PATH or run:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
  fi
}

# ── Run ─────────────────────────────────────────────────
detect_os
ensure_python
ensure_git
install_paganini
setup_env
create_wrapper
verify

cat << 'DONE'

  ┌──────────────────────────────────────────────┐
  │                                              │
  │   ✓ PAGANINI installed successfully!         │
  │                                              │
  │   Get started:                               │
  │                                              │
  │     paganini init --pack fidc                │
  │     paganini up                              │
  │                                              │
  │   Or with Docker:                            │
  │                                              │
  │     paganini init --mode docker              │
  │     docker compose up                        │
  │                                              │
  │   Docs: https://github.com/juboyy/           │
  │         paganini-aios/tree/main/docs         │
  │                                              │
  └──────────────────────────────────────────────┘

DONE
