apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paganini.fullname" . }}-secrets
  labels:
    {{- include "paganini.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.provider.apiKey | quote }}
